"""
recommendation_service.py — Recommendation text logic.

Rules:
  - If mitigation section NOT selected in report options:
      recommendation_text = GENERIC_PPE_TEXT (static fallback)
  - If mitigation section IS selected:
      Use the auto_conclusion logic (passed in) or user override.

Future FastAPI: GET /recommendation-text?mitigation=true|false
"""

GENERIC_PPE_TEXT = (
    "Use Recommended PPE while doing any work with energized equipment."
)

MITIGATION_RECOMMENDATION_TEXT = (
    "If protective devices are set with FCT ≤ 0.08 s, incident energy can be "
    "reduced to Level D or below. Maintenance mode settings are recommended for "
    "protective devices at high-energy bus locations."
)


def get_recommendation_text(
    show_mitigation_section: bool,
    auto_text: str = "",
    user_override: str = "",
) -> str:
    """
    Return the final recommendation text.

    Args:
        show_mitigation_section: True if the user opted to include the
            mitigation/maintenance section in the report.
        auto_text: Text generated by auto_conclusion (only used when
            show_mitigation_section=True).
        user_override: Explicit text entered by the user (takes priority
            over auto_text when non-empty).

    Returns:
        Final recommendation string to embed in the report.
    """
    if user_override:
        return user_override

    if not show_mitigation_section:
        return GENERIC_PPE_TEXT

    # Mitigation section is included — use auto or mitigation text
    return auto_text or MITIGATION_RECOMMENDATION_TEXT


def get_mitigation_text(
    show_mitigation_section: bool,
    auto_text: str = "",
    user_override: str = "",
) -> str:
    """
    Return the mitigation paragraph text ({{mitigation_text}} field).

    If mitigation section not selected → empty string (field is suppressed
    or left blank in the template).
    """
    if not show_mitigation_section:
        return ""
    if user_override:
        return user_override
    return auto_text
